# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This Source Code Form is "Incompatible With Secondary Licenses", as
# defined by the Mozilla Public License, v. 2.0.

version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
